In [1]:
import numpy as np
import tensorflow as tf

2022-01-26 21:11:58.089469: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


## tf.Tensor vs np.array

Tensors are a type of array used by Tensorflow. They have a lot in common with numpy arrays.

In [2]:
arr = np.array([[1, 2, 5], [5,7,3]])

In [3]:
arr

array([[1, 2, 5],
       [5, 7, 3]])

Convert a numpy array to a Tensorflow tensor with the following line:

In [4]:
tensor = tf.convert_to_tensor(arr)

2022-01-26 21:12:43.587682: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-01-26 21:12:43.609272: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-26 21:12:43.609535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:21:00.0 name: GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.71GHz coreCount: 68 deviceMemorySize: 9.78GiB deviceMemoryBandwidth: 707.88GiB/s
2022-01-26 21:12:43.609548: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-01-26 21:12:43.623522: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-01-26 21:12:43.623551: I tensorflow/stream_executor/platform/de

Access the numpy array by using `.numpy()`

In [5]:
tensor.numpy()

array([[1, 2, 5],
       [5, 7, 3]])

Tensors and array share some attributes, such as shape.

In [6]:
arr.shape

(2, 3)

In [7]:
tensor.shape

TensorShape([2, 3])

## Operations on tensors

Similarly to np.arrays, we can perform operation on tensors.

In [ ]:
tensor

Element-wise multiplication

In [8]:
tensor*2

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 2,  4, 10],
       [10, 14,  6]])>

Broadcasting rules apply.

In [9]:
tensor*tf.constant([3, 2, 2], dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 3,  4, 10],
       [15, 14,  6]])>

## Additional attribute & methods

Find the tensor location

In [10]:
tensor.device

'/job:localhost/replica:0/task:0/device:CPU:0'

Move tensor to the gpu by calling `tensor.gpu()`

In [11]:
tensor.gpu()

Instructions for updating:
Use tf.identity instead.


<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>

In [12]:
tf.identity(tensor)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>